IF NOT EXISTS (
SELECT *
FROM SYS.INDEXES
WHERE NAME='IX_Name_Currency' AND OBJECT_ID = OBJECT_ID('DBO.Player')
)
BEGIN
	CREATE INDEX ix_Name_Currency ON dbo.Player(Name,Currency)
	WITH(DATA_COMPRESSION=ROW,MAXDOP=8,ONLINE= ON)
END
/*
IF EXISTS (
SELECT *
FROM SYS.INDEXES
WHERE NAME='IX_Name_Currency' AND OBJECT_ID = OBJECT_ID('DBO.Player')
)
BEGIN
    ALTER INDEX IX_Name_Currency on DBO.Player REBUILD 
    WITH (MAXDOP=8,ONLINE = ON(WAIT_AT_LOW_PRIORITY 
		(MAX_DURATION = 1 MINUTES , ABORT_AFTER_WAIT = SELF )))
	--DROP_EXISTING = ON
END
*/