IF NOT EXISTS (
SELECT *
FROM SYS.INDEXES
WHERE NAME='IX_Balance' AND OBJECT_ID = OBJECT_ID('DBO.Wallet')
)
BEGIN
  CREATE INDEX IX_Balance ON dbo.Wallet(Balance)
  WITH(DATA_COMPRESSION=ROW,MAXDOP=8,ONLINE= ON)
END
/*
IF EXISTS (
SELECT *
FROM SYS.INDEXES
WHERE NAME='ix_Balance' AND OBJECT_ID = OBJECT_ID('DBO.Wallet')
)
BEGIN
   ALTER INDEX ix_Balance on DBO.Wallet REBUILD 
    WITH (MAXDOP=8,ONLINE = ON(WAIT_AT_LOW_PRIORITY 
		(MAX_DURATION = 1 MINUTES , ABORT_AFTER_WAIT = SELF )))
END
*/